//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdminID { get; set; }
        public string AdminFullName { get; set; }
        public Nullable<int> PrivateAdminID { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPassword { get; set; }
        public string AdminValidPassword { get; set; }
        public Nullable<System.DateTime> AdminBirthDate { get; set; }
        public string AdminImage { get; set; }
        public string AdminGender { get; set; }
        public string AdminUserName { get; set; }
        public string AdminAuthorization { get; set; }
    }
}
