//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public Nullable<int> PrivateEmployeeID { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeValidPassword { get; set; }
        public Nullable<System.DateTime> EmployeeBirthDate { get; set; }
        public string EmployeeImage { get; set; }
        public string EmployeeGender { get; set; }
        public string EmployeeUserName { get; set; }
        public string EmployeeAuthorization { get; set; }
    }
}
