//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleArea()
        {
            this.VehicleRentAreas = new HashSet<VehicleRentArea>();
        }
    
        public int VehicleAreaID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> CurrentKMPH { get; set; }
        public string IsAvailable { get; set; }
        public string IsProper { get; set; }
        public Nullable<int> LicenseNum { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string VehicleAreaImage { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRentArea> VehicleRentAreas { get; set; }
    }
}
