//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleType()
        {
            this.VehicleAreas = new HashSet<VehicleArea>();
        }
    
        public int VehicleTypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> DayCost { get; set; }
        public Nullable<decimal> LateDayCost { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public string Gear { get; set; }
        public string Class { get; set; }
        public string VehicleImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleArea> VehicleAreas { get; set; }
    }
}
